version: '3'
services:
  mondodb:
    container_name: mongodb
    image: mongo:4.1
    ports:
      - "27017:27017"
    volumes:
      - "/mnt/DATAEXT/mongo/:/data/db/"

  mongo-express:
    image: mongo-express
    container_name: mongodbexpress
    ports:
      - 7776:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  default:
    external:
      name: bot_network