version: '3'
services:
  # container_raspberry:
  #   build: ./containers/raspberry-strech/
  #   image: raspberry_bot:latest
  #Not working in raspberry pi3  
  container_raspberry_alpine:
    build: ./containers/raspberry-alpine/
    image: raspberry_bot_alpine:latest
  #BOTS GO HERE
  # grcanosabot:
  #   image: raspberry_bot:latest
  #   restart: always
  #   container_name: botsrv_grcanosabot
  #   network_mode: host
  #   volumes:
  #     - "./shared/:/mnt/shared/"
  #     - "./data/:/mnt/data/"
  #     - "./src/:/code/" 
  #   entrypoint:
  #     - python3
  #     - grcanosabot/grcanosabot.py
  #     - --dataloc=/mnt/data/
  #     - --dbloc=/mnt/shared
  selenium:
    #image: selenium/standalone-firefox:3.141.59-titanium
    image: selenium/standalone-chrome:3.141.59-titanium
    #image: selenium/standalone-chrome-debug:3.141.59-titanium
    # ports:
    #   - "5900:5900"
    container_name: selenium
    volumes:
      - "/dev/shm:/dev/shm"
  renfebot:
    image: raspberry_bot_alpine:latest
    restart: always
    container_name: botsrv_renfebot
    #network_mode: host
    volumes:
      - "./shared/:/mnt/shared/"
      - "./src/:/code/"
      - "./submodules/:/submodules/" 
      - "/etc/timezone:/etc/timezone:ro"
    entrypoint:
      - python3
      - renfebot/renfebot.py
networks:
  default:
    external:
      name: bot_network